# fly.toml app configuration file generated for hooktest-dry-sun-421 on 2025-07-21T14:36:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hooktest-dry-sun-421'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 8000
    handlers = ['http']

  [[services.ports]]
    port = 8001
    handlers = ['tls', 'http']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
